include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += 
LOCAL_SRCS      += drv_security.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

