include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += 
LOCAL_SRCS      += l2_packet_rtos.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

