include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += 
LOCAL_SRCS      += common.c eloop_rtos.c os_rtos.c wpa_debug.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

