include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += 
LOCAL_SRCS      += wpa_common.c defs.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

