include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += drv_dma.c drv_pkt_dma.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

