include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += 
LOCAL_SRCS      += aes-internal.c \
                   aes-internal-dec.c \
                   aes-internal-enc.c \
                   aes-unwrap.c \
                   crypto_internal.c \
                   md5.c \
                   md5-internal.c \
                   rc4.c \
                   sha1.c \
                   sha1-internal.c \
                   sha1-pbkdf2.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

