include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += common crypto drivers rsn_supp utils
LOCAL_SRCS      += events.c wpa_supplicant.c wpas_glue.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

