include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += cmds #verify
LOCAL_SRCS      += cli.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

