include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += supplicant
LOCAL_SRCS      += cmd_engine.c soft-main.c  sta_info.c util.c SmartConfig.c mlme.c MLME_Task.c MLME_Scan.c MLME_Join.c MLME_Leave.c edca.c MLME_PwrSaving.c \
		   edca_queue.c pide_algo.c psk_cache.c ssv_pkt.c
#l34cs.c defrag.c agg_rx.c test_sdio.c 

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

