include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += 
LOCAL_SRCS      += wpa.c wpa_ie.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

