include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += cli_cmd.c cli_cmd_monitor.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

