include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += #cli_cmd_rtc.c cli_cmd_l34cs.c cli_cmd_txrx.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

