include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += uart
SRC_DIRS        += timer
SRC_DIRS        += rtc
SRC_DIRS        += mbox
SRC_DIRS        += idmanage
SRC_DIRS        += hwmac
SRC_DIRS        += dbg_timer
SRC_DIRS        += edca
#SRC_DIRS        += dma
SRC_DIRS        += pmu
#SRC_DIRS        += l34csum
SRC_DIRS        += nav
SRC_DIRS        += beacon
SRC_DIRS        += random
#SRC_DIRS        += math
SRC_DIRS        += phy
SRC_DIRS        += security
SRC_DIRS        += ampdu
#SRC_DIRS        += flash
#SRC_DIRS        += efuse
#LOCAL_SRCS      += hw_regs_api.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

