include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += bsp.c cpu.c irq.c serial.c
LOCAL_ASMS	+= boot.S

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

